### ISSUE TITLE
Dejar de utilizar forks de las dependencias de python

### ISSUE THREAD

**Issue by LuisAlejandro** [LuisAlejandro/tribus#58]
<a href="https://github.com/LuisAlejandro"><img src="https://avatars0.githubusercontent.com/u/324683?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LuisAlejandro](https://github.com/LuisAlejandro)**
_Tuesday Jun 24, 2014 at 22:15 GMT_
_Originally opened as https://github.com/TribusGNULinux/tribus/issues/69_

----

Mantener forks de las dependencias de python debido a que los proyectos originales contienen errores o ciertas funcionalidades están ausentes, representa un problema a largo plazo. Significa una carga de mantenimiento adicional que puede resultar en dependencias desactualizadas si se descuida.

Actualmente se utilizan tres forks:
1. [django-tastypie-mongoengine](https://github.com/LuisAlejandro/django-tastypie-mongoengine/compare/wlanslovenija:master...master): Se utiliza porque el proyecto original restringe la version de mongoengine y Tribus necesita una versión superior.
2. [xapian-haystack](https://github.com/joseguerrero/xapian-haystack/compare/notanumber:master...master): Se utiliza porque los tipos de búsqueda ngram y edge_ngram fueron removidos en una versión anterior, causando que la búsqueda en el índice fuese inadecuada para Tribus.
3. [django-static](https://github.com/joseguerrero/django-static/compare/peterbe:master...master): Se utiliza para agregar un parámetro a una función que permite alargar los nombres de los archivos estáticos que se unifican con django-static. Cuando el largo del nombre es muy corto, los archivos estáticos unificados pueden sobreescribirse entre ellos si los primeros 4 o 5 archivos son los mismos.

**Comment by LuisAlejandro** [comment]
<a href="https://github.com/LuisAlejandro"><img src="https://avatars0.githubusercontent.com/u/324683?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LuisAlejandro](https://github.com/LuisAlejandro)**
_Sunday Jun 29, 2014 at 17:00 GMT_

----

Las posibles soluciones a cada caso pueden ser:
- [x] **django-tastypie-mongoengine**: Está relacionado con el ticket #62. Cuando dejemos de usar Mongo, esta dependencia será innecesaria.
- [ ] **xapian-haystack**: Se puede seguir insistiendo en el pull request notanumber/xapian-haystack#117 para que la solución sea mezclada con upstream, o podemos hacer un [monkeypatch](https://filippo.io/instance-monkey-patching-in-python/) del método. Si hacemos un monkeypatch, igualmente hay que seguir insistiendo en el pull request.
- [ ] **django-static**: Está relacionado con el ticket #64. Cuando utilicemos la librería javascript _Modernizr_, será innecesario utilizar esta dependencia.
