### ISSUE TITLE
Iniciar la migración a Python 3

### ISSUE THREAD

**Issue by LuisAlejandro** [LuisAlejandro/tribus#59]
<a href="https://github.com/LuisAlejandro"><img src="https://avatars0.githubusercontent.com/u/324683?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LuisAlejandro](https://github.com/LuisAlejandro)**
_Tuesday Jun 24, 2014 at 22:17 GMT_
_Originally opened as https://github.com/TribusGNULinux/tribus/issues/70_

----

Según la plataforma [Requires.io](https://requires.io/github/tribusdev/tribus/requirements/?branch=development), las siguientes dependencias de Tribus aún faltan por migrar a Python3:
1. celery-haystack
2. celery-with-redis
3. cssmin
4. django-ldapdb
5. django-registration
6. django-waffle
7. fabric
8. mondogdbforms
9. python-debian
10. slimit

Además, la propia base de código de Tribus aún no ha sido migrada. Poniéndonos como meta que Tribus debe soportar (al menos) 3 versiones  python, queremos dar soporte a python 2.6, 2.7 y 3.4 (ya se soporta python 2.6 y 2.7).

Acá se puede consultar documentación acerca de los métodos a seguir para realizar la migración:
- http://python3porting.com
- https://docs.python.org/3/howto/pyporting.html

**Comment by LuisAlejandro** [comment]
<a href="https://github.com/LuisAlejandro"><img src="https://avatars0.githubusercontent.com/u/324683?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LuisAlejandro](https://github.com/LuisAlejandro)**
_Wednesday Jun 25, 2014 at 05:55 GMT_

----

Dentro de las posibles soluciones para cada una de las dependencias que aún faltan para migrar a Python 3.4, tenemos:
1. [x] celery-haystack: Hay que hacerle seguimiento a este pull request jezdez/celery-haystack#27.
2. [x] celery-with-redis: Esta dependencia fue removida en el commit 6390c1ee7f75850244f948ba4e607abab5eed958.
3. [ ] cssmin: Cuando empecemos a usar Grunt, debido al ticket #74, podemos empezar a utilizar una solución basada en javascript y quitar esta dependencia. Por ejemplo, [assets-packager](https://github.com/GoalSmashers/assets-packager). Si se quita cssmin también debe quitarse slimit y reescribir los comandos de compresión en `tribus/common/setup/build`.
4. [ ] django-ldapdb: Hay algún soporte para python3 en [ramas experimentales](https://twitter.com/raphaelbarrois/status/483388488851918848).
5. [ ] django-registration: Hay que reemplazar esta dependencia, [el mantenedor se retiró](https://bitbucket.org/ubernostrum/django-registration/wiki/Home). Un posible reemplazo: [django-allauth](http://django-allauth.readthedocs.org/en/latest/)
6. [x] django-waffle: Prestar atención a jsocol/django-waffle#113.
7. [ ] fabric: Prestar atención a fabric/fabric#1050.
8. [x] mondogdbforms: Esta dependencia será removida cuando se complete el ticket #62.
9. [ ] python-debian: La versión con soporte a python3 no está en pypi ni en Wheezy.
10. [ ] slimit: Debe quitarse junto con cssmin en el ticket #74.

**Comment by LuisAlejandro** [comment]
<a href="https://github.com/eirnym"><img src="https://avatars2.githubusercontent.com/u/485399?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eirnym](https://github.com/eirnym)**
_Friday Sep 26, 2014 at 11:52 GMT_

----

Finished:
https://github.com/tribusdev/tribus/issues/62
https://github.com/fabric/fabric/issues/1050
https://github.com/jsocol/django-waffle/pull/113
https://github.com/jezdez/celery-haystack/pull/27

**Comment by LuisAlejandro** [comment]
<a href="https://github.com/LuisAlejandro"><img src="https://avatars0.githubusercontent.com/u/324683?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LuisAlejandro](https://github.com/LuisAlejandro)**
_Friday Sep 26, 2014 at 18:44 GMT_

----

Thanks @eirnym, we'll be adressing this as soon as possible :-)
